version: "3"
services:
  db:
    image: postgres:9.6-alpine
    expose:
      - "5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: sharecar
      POSTGRES_PASSWORD: sharecar
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db