default: &default
  adapter: postgresql
  encoding: utf8
  database: sharecar
  pool: 5

development:
  <<: *default
  host: 127.0.0.1
  username: sharecar
  password: sharecar

test:
  <<: *default
  host: 127.0.0.1
  database: sharecar-test
  username: sharecar
  password: sharecar